package main

var KeywordMap = map[string]bool {
    "boolean": true,
    "char": true,
    "class": true, 
    "constructor": true, 
    "do": true,
    "else": true,
    "false": true,
    "field": true, 
    "function": true, 
    "if": true,
    "int": true, 
    "let": true,
    "method": true, 
    "null": true,
    "return": true,
    "static": true, 
    "this": true,
    "true": true,
    "var": true, 
    "void": true,
    "while": true,
}

var SymbolMap = map[string]bool {
    "{": true,
    "}": true,
    "(": true,
    ")": true,
    "[": true,
    "]": true,
    ".": true,
    ",": true,
    ";": true,
    "+": true,
    "_": true,
    "*": true,
    "/": true,
    "&": true,
    "|": true,
    "<": true,
    ">": true,
    "=": true,
    "-": true,
}
